package website.lihan.temu;

import com.oracle.truffle.api.CallTarget;
import com.oracle.truffle.api.Option;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.TruffleLanguage.ContextPolicy;
import com.oracle.truffle.api.nodes.Node;
import com.oracle.truffle.api.object.Shape;
import com.oracle.truffle.api.strings.TruffleString;
import java.util.ArrayList;
import org.graalvm.options.OptionCategory;
import org.graalvm.options.OptionDescriptors;
import org.graalvm.options.OptionKey;
import org.graalvm.options.OptionStability;
import website.lihan.temu.cpu.Rv64ExecutionRootNode;
import website.lihan.temu.device.Bus;
import website.lihan.temu.device.FbDev;
import website.lihan.temu.device.Keyboard;
import website.lihan.temu.device.Memory;
import website.lihan.temu.device.RTC;
import website.lihan.temu.device.SerialPort;

@TruffleLanguage.Registration(
    id = Rv64BytecodeLanguage.ID,
    name = "RISC-V Bytecode (rv64im_zicsr)",
    contextPolicy = ContextPolicy.SHARED,
    defaultMimeType = "application/x-rv64-bytecode",
    byteMimeTypes = {"application/x-rv64-bytecode"})
public final class Rv64BytecodeLanguage extends TruffleLanguage<Rv64Context> {
  public static final String ID = "rv64";

  public static final TruffleString.Encoding STRING_ENCODING = TruffleString.Encoding.UTF_16;
  private static final LanguageReference<Rv64BytecodeLanguage> REF =
      LanguageReference.create(Rv64BytecodeLanguage.class);

  @Option(
      help = "Enables common devices for GUI support",
      category = OptionCategory.USER,
      stability = OptionStability.STABLE)
  static final OptionKey<Boolean> gui = new OptionKey<>(false);

  @Option(
      help = "Maps a file to a memory region",
      category = OptionCategory.USER,
      stability = OptionStability.EXPERIMENTAL)
  static final OptionKey<Long> memory_region = new OptionKey<>(0L);

  public final Shape attrsetShape = Shape.newBuilder().build();

  public static Rv64BytecodeLanguage get(Node node) {
    return REF.get(node);
  }

  @Override
  protected CallTarget parse(ParsingRequest request) throws Exception {
    var source = request.getSource();

    var bytecode = source.getBytes().toByteArray();
    var evalRootNode = new Rv64ExecutionRootNode(this);
    var context = Rv64Context.get(evalRootNode);
    context.getBus().executeWrite(0x80000000L, bytecode, bytecode.length);

    return evalRootNode.getCallTarget();
  }

  @Override
  protected Object getScope(Rv64Context context) {
    return context.createScopeObject();
  }

  @Override
  protected Rv64Context createContext(Env env) {
    var devices = new ArrayList<Object>();

    if (env.getOptions().hasBeenSet(memory_region)) {
      var memoryRegion = env.getOptions().get(memory_region);
      var memory = new Memory(memoryRegion, 16 * 1024 * 1024);
      devices.add(memory);
    } else {
      var memory = new Memory();
      devices.add(memory);
    }

    if (env.getOptions().hasBeenSet(gui) && env.getOptions().get(gui)) {
      var keyboard = new Keyboard();
      var fbdev = new FbDev();
      var gui = new EmulatorGUI();
      gui.connect(keyboard);
      gui.connect(fbdev);
      gui.show();
      devices.add(keyboard);
      devices.add(fbdev.getControl());
      devices.add(fbdev.getFrameBuffer());
    }

    devices.add(new SerialPort());
    devices.add(new RTC());

    var context = new Rv64Context(this, new Bus(devices.toArray()));
    return context;
  }

  @Override
  protected OptionDescriptors getOptionDescriptors() {
    // this class is generated by the annotation processor
    return new Rv64BytecodeLanguageOptionDescriptors();
  }
}
